<style>
form {
    width: 50%;
}
</style>
<form method="POST" action="/mage/crud/index/save">
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" class="form-control" id="name"  >
  </div>
  <br>
  <div class="form-group">
    <label for="post_content">Content</label>
    <input type="text" class="form-control" id="post_content" name="post_content">
  </div>
  <br>
  <button type="submit" class="action primary">Submit</button>
</form>